Megami_project/Megami_app/urls.py
from django.urls import path
# from .views import IndexView
from django.contrib.auth import authenticate, login

from django.urls import path
from django import views
from .views import PostDetailView, CreatePostView
from Megami_app import views
## アプリケーション名
app_name = 'Megami_app'
## URLのパターンを定義するためのもの
urlpatterns = [
    path('',views.IndexView.as_view(), name='home'),
    path('post/<int:pk>/' ,views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/' ,views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/' ,views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/' ,views.PostDeleteView.as_view(), name='post_delete'),

    path('change/', views.add_good_count_for_article, name='change_count'),

]

Megami_project/Megami_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from Megami_app import views
from Megami_account import views

from django.conf import settings
from django.conf.urls.static import static




home_view = TemplateView.as_view(template_name = "home.html")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Megami_app.urls')),
    path('', login_required(home_view), name="home"),
    path('', include('django.contrib.auth.urls')),

    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name="activate"),
    path('change_user/', views.ProfileEditView.as_view(), name="change_user"),

    path('<slug:username>/', views.ProifileDetail.as_view(), name='detail'),
    path('<slug:username>/follow', views.follow_view, name='follow'),
    path('<slug:username>/unfollow', views.unfollow_view, name='unfollow'),
    # path('post/<int:pk>',views.PostDetailView.as_view(), name="post_detail")
    
    # path('followuser/', views.followuser, name='followuser'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Megami_project/Megami_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

## 投稿モデル
class Post(models.Model):
   title = models.CharField('タイトル', max_length=50)
   content = models.TextField('本文')
   image = models.ImageField('画像', upload_to='images', blank=True)
   created_at = models.DateTimeField('投稿日', default=timezone.now)
   user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   good_count = models.IntegerField(default=0)

   def __str__(self):
       return self.title

Megami_project/Megami_app/forms.py
from django import forms
from .models import Post
from django.forms import ModelForm


class PostForm(forms.Form):
    title = forms.CharField(max_length=30, label='タイトル')
    content = forms.CharField(label='内容', widget=forms.Textarea())
    image = forms.ImageField(label='イメージ画像', required=False) # 追加

Megami_project/Megami_app/views.py
# from django.views.generic import TemplateView,ListView
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import PostForm
from .models import Post
from Megami_account.models import  Connection
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse
from django.http import JsonResponse
from django.views.generic.edit import CreateView

class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        action = request.GET.get('action')
        if action == "new":
            post_data = Post.objects.order_by('-id')
        else: 
            post_data = Post.objects.order_by('-good_count')
        user_follower = Connection.objects.filter(following=user.id).all()
        user_following = Connection.objects.filter(follower=user.id).all()
        return render(request, 'home.html',{
            'post_data':post_data,
            'user_follower':user_follower,
            'user_following':user_following
        })


# class VoteView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):






class PostDetailView(View):
    def get(self, request, *args, **kwargs):
        post_data = Post.objects.get(id=self.kwargs['pk'])
        return render(request, 'post_detail.html',{
            'post_data': post_data
        })

class CreatePostView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = PostForm(request.POST or None)

        return render(request, 'post_form.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST or None)

        if form.is_valid():
            post_data = Post()
            post_data.user = request.user
            post_data.title = form.cleaned_data['title']
            post_data.content = form.cleaned_data['content']
            if request.FILES:
                post_data.image = request.FILES.get('image') # 追加
            post_data.save()
            
            return redirect('Megami_app:post_detail', post_data.id)

        return render(request, 'post_form.html', {
            'form': form
        })


class PostEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post_data = Post.objects.get(id=self.kwargs['pk'])
        form = PostForm(
            request.POST or None,
            initial={
                'title': post_data.title,
                'content': post_data.content,
                'image': post_data.image, # 追加
            }
        )
        return render(request, 'post_form.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST or None)
        if form.is_valid():
            post_data = Post.objects.get(id=self.kwargs['pk'])
            post_data.title = form.cleaned_data['title']
            post_data.content = form.cleaned_data['content']
            if request.FILES:
                post_data.image = request.FILES.get('image') # 追加
            post_data.save()
            return redirect('Megami_app:post_detail', self.kwargs['pk'])
        return render(request, 'post_form.html', {
            'form': form
        })

class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post_data = Post.objects.get(id=self.kwargs['pk'])
        return render(request, 'post_delete.html',{
            'post_data': post_data
        })
    
    def post(self, request, *args, **kwargs):
        post_data = Post.objects.get(id=self.kwargs['pk'])
        post_data.delete()
        return redirect('home')
    

# テスト
# class ArticleCreateView(CreateView):
#     model = Post
#     fields = ('title', )
    
#     def get_success_url(self):
#         return reverse('article:article_list')

def add_good_count_for_article(request):
    article_id = request.POST.get('id')
    article = Post.objects.get(id=article_id)

    article.good_count += 1
    article.save()
    data = {
        'id': article_id,
        'good_count': article.good_count,
    }
    return JsonResponse(data)


def chat( request ):
    return render( request, '' )

Megami_project/Megami_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- フォント -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif:ital@1&family=Quattrocento:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    {% block style %}
    
    {% endblock %}
    <title>Megami</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
    <footer>
        <div class="footer">
            <h1 class="footer-logo">Megami</h1>
            <ul class="footer-menu">
                <li>Home</li>
                <li>サイトマップ</li>
                <li>プライポリシー</li>
                <li>ご利用にあたって</li>
            </ul>
            <ul class="footer-list">
                <li>FAQ</li>
                <li>ご意見</li>
                <li>KAMUI</li>
                <li class="icon-container">
                    SNS
                    <img src="{% static 'IMG/base_img/facebook_icon.png' %}">
                    <img src="{% static 'IMG/base_img/Twitter_Icon.png' %}">
                    <img src="{% static 'IMG/base_img/instagram_icon.png' %}">
                    <img src="{% static 'IMG/base_img/Pinterest_icon.png' %}">

                </li>
            </ul>
        </div>
    </footer>
</body>

</html>

Megami_project/Megami_app/templates/conf.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'CSS/conf.css' %}">
{% endblock %}
{% block content %}
<main >
    <div class="main">
        <div class="header">
            <h1 class="megami-logo header-item"><a href="/" class="logo">Megami</a></h1>
        </div>
        
        <div class="signin">
            <h1><img src="{% static 'IMG/signin_img/upper_body-1.png' %}" id="user_icon" alt="User" >アカウント登録</h1>
        </div>
        <div class="news-container">
            <h1>登録ありがとうございます。</h1>
        </div>
        <div class="sub-container">
            <h2>この状態はまだ仮登録です。</h2>
            <p>会員登録確認メールを送信しました。</p>
            <p>確認メールに記載されているリンクから本登録を行なってください。</p>
        </div>
        
    </div>
</main>
{% endblock %}

Megami_project/Megami_app/templates/home.html
{% extends "base.html" %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'CSS/home.css' %}">
    {% endblock %}
    {% block content %}
    <header>
        <div class="header">
            <div class="header-menu">
                <h1 class="megami-logo header-item"><a href=" " class="logo">Megami</a></h1>
            </div>
            <div class="header-account_menu">
                <a href="{% url 'Megami_app:post_new' %}"><p>
                <i class="fas fa-paper-plane" id="post_form" class="post_form"></i></p></a>
                <h2>
                    {% if user.image %}
                    <div class="icon_area_img" id="account_icon">
                        <img src="{{ user.image.url }}">
                    </div>
                    {% else %}
                        <i class="fas fa-user-circle" id="account_icon"></i>
                    {% endif %}
                </h2>
            </div>
            <account class="account show">
                <div class="profile-aria">
                    <div class="profile">
                        <h2>プロフィール</h2>
                        <i class="fas fa-times" id="x_icon"></i>
                        <div style="border-bottom: solid 2px black; "></div>
                        <div class="icon_area">
                            {% if user.image %}
                                <img src="{{ user.image.url }}">
                            {% else %}
                                <img src="{% static 'IMG/home_img/icons8-user-64.png' %}">
                            {% endif %}
                        </div>
                        <div class="fast-name">
                            <p>{{user.first_name}}</p>
                            <p>{{user.last_name}}</p>
                        </div>
                        <div class="username">
                            <p class="myuser">{{user.username}}</p>
                        </div>
                        <div class="email">
                            <h3>Email:</h3>
                            <p>{{user.email}}</p>
                        </div>
                        <div class="introduction">
                            <h3>Comment</h3>
                            <div class="comment_container">
                                <p>{{user.description}}</p>
                            </div>
                        </div>
                        <div class="change_account">
                            <a class="ui button" href="{% url 'change_user' %}">変更</a>
                            <a href="{% url 'logout' %}">ログアウト</i></a>
                        </div>
                        
                    </div>
                </div>
            </account>
        </div>
    </header>
    
    <main class="main">
            <div class="user_stories">
                <h1>Schedule</h1>
                <div class="user_image_area user_follower">
                    <div class="following">
                        {% for user_follow in user_following %}
                        <div class="follow_data">
                            {% if user_follow.following.image %}
                                <img class="following_data" id={{user_follow.following.id}} src="{{ user_follow.following.image.url }}" alt=""/>
                            {% else %}
                                <img class="following_data" id={{user_follow.following.id}} src="{% static 'IMG/home_img/icons8-user-64.png' %}">
                            {% endif %}
                            <h3 class="following_data">
                                <a href="/{{user_follow.following.username}}/">
                                    {{user_follow.following.username}}
                                </a>
                            </h3>
                        </div>
                        {% endfor %}
                    </div>  
                </div>
            </div>
            <div class="post_container">
                <div class="post_sort">
                    <form class="post_sort_form" method="GET" action="{% url 'home' %}">
                        {% csrf_token %}
                        <button type="submit" name="action" value="new">New</button>
                        <br>
                        <br>
                        <button type="submit" name="action" value="popularity">Pop</button>
                    </form>
                </div>
                <div class="post-area">
                    {% for post in post_data %}
                    <div class="post">
                        <center>
                            {% if post.image %}
                            <div class="post-image_area">
                                <img src="{{ post.image.url }}" alt="" />
                            </div>
                            {% else %}
                            <p>image none</p>
                            {% endif %}
                        </center>
                        <div class="post_title">
                            <h2>{{ post.title }}</h2>
                        </div>
                        <div class="post_content">
                            <p>{{ post.content|truncatechars:100 }}</p>
                        </div>
                        <div class="more_sea"><a href="{% url 'Megami_app:post_detail' post.id %}">もっと見る<i class="fas fa-angle-right"></i></a></div>
                        <div class="post_user">
                            <p class="post_data">
                                {% if user.icon == null%}
                                    <img  class="icon-img" src="/media/{{ post.user.image }}">
                                {% else %}
                                    <img src="{% static 'IMG/home_img/icons8-user-64.png' %}">
                                {% endif %}
                                {{ post.user }}</p>
                            <div class="LikesIcon add_good">
                                <i class="far fa-heart LikesIcon-fa-heart" id={{ post.id }}></i>
                            </div>
                            <p class="post_data date">{{ post.created_at|date }}</p>
                        </div>
                        <center>
                            <div class="user_line"></div>
                        </center>
                    </div>
                    {% endfor %}
                </div>

                <Schedule class="stories action" >
                    <i class="fas fa-times" id="x_icon1"></i>
                    <div class="stories_menu">
                        
                    </div>
                </Schedule>


                <chat class="chat">
                    <div id="div_container">
                        <h1>Chat</h1>
                        <div id="div_main">
                            <div id="div_join_screen">
                                <!-- エンターキーによるボタン押下を行うために、<button>ではなく<form>と<input type="submit">を使用。
                                ボタン押下(=submit)時にページリロードが行われないように、onsubmitの設定の最後に"return false;"を追加。-->
                                <form action="" onsubmit="onsubmitButton_JoinChat(); return false;" class="chat_join_form" >
                                    <div class="chat_user_name">
                                        <h3>User name</h3>
                                        <input type="text" id="input_username" placeholder="Enter User name" value="{{user.username}}" autofocus>
                                    </div>
                                    <div class="chat_room_name">
                                        <h3>Room name</h3>
                                        <input type="text" id="input_roomname" placeholder="Enter Room name">
                                    </div>
                                    <div class="help_message">
                                        Room name must be a string containing only ASCII alphanumerics, hyphens, or periods.
                                    </div>
                                    <input type="submit" value="Join Chat" class="join_submit"/>
                                </form>
                            </div>
                
                            <div id="div_chat_screen">
                                <button class="chat_button" onclick="onclickButton_LeaveChat()"><i class="fas fa-running"></i>Leave Chat</button>
                                <div class="chat_user_name">
                                    <h3>User</h3>
                                    <input type="text" id="text_username" readonly="readonly">
                                </div>
                                <div class="chat_room_name">
                                    <h3>Room</h3>
                                    <input type="text" id="text_roomname" readonly="readonly">
                                </div>
                                <!-- エンターキーによるボタン押下を行うために、<button>ではなく<form>と<input type="submit">を使用。
                                ボタン押下(=submit)時にページリロードが行われないように、onsubmitの設定の最後に"return false;"を追加。-->
                                <form action="" onsubmit="onsubmitButton_Send(); return false;">
                                    <div class="chat_message">
                                        <h3>Message</h3>
                                    </div>
                                    <div class="chat_send">
                                        <input type="text" id="input_message" maxlength="45" autocomplete="off" autofocus />
                                        <input type="submit" value="Send" class="message_send"/>
                                    </div>
                                    
                                </form>
                
                                <ul id="list_message">
                                    <div class="user_div">

                                    </div>
                                </ul>
                            </div>
                        </div>
                    </div>
                </chat>


                <video_chats class="video_chats">
                    <div class="container">
                        <h1 class="heading">Meeting</h1>
                        <div class="room">
                            <div>
                                <div id="local-stream">
                                    <video id="js-local-stream" class="local-stream show"></video>
                                </div>
                                <button class="video_on" onclick="OnButtonClick();">Start</button>
                                <button class="video_off show" onclick="OffButtonClick();">Stop</button>
                                    
                                <div class="room_inout">
                                    <input type="text" placeholder="Room Name" id="js-room-id">
                                <button id="js-join-trigger">Join</button>
                                <button id="js-leave-trigger">Leave</button>
                                </div>
                            </div>
                            <div class="remote-streams" id="js-remote-streams"></div>
                            <div class="remote_message">
                                <pre class="messages" id="js-messages"></pre>
                                <input type="text" id="js-local-text">
                                <button id="js-send-trigger">Send</button>
                            </div>
                        </div>
                    </div>
                </video_chats>

            </div>
    </main>



    <!-- テスト -->

    <div class="test">

    </div>

    
    <!-- テスト -->
    

    <script src="https://cdn.webrtc.ecl.ntt.com/skyway-4.4.3.js"></script>
    <script type="text/javascript" src="{% static 'JS/home.js' %}"></script>
    {% endblock %}

Megami_project/Megami_app/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
{% endblock %}
{% block content %}
    <header>
        <div class="header">
            <div class="header-menu">
                <h1 class="megami-logo header-item"><a href=" " class="logo">Megami</a></h1>
                <div class="signin-button header-item">
                    <button class="login-btn"> <span><a href="signin/">Signin</a></span> </button>
                </div>
            </div>
            <div class="audience-area">
                <div class="signin-message">
                    <h2 id="connect-message" class="connect-message">Let's connect ! !</h2>
                    <h2 id="using-message" class="using-message">using Megami</h2>
                </div>
                <div class="btn">
                    <button class="login-btn"> <span>Get started</span> </button>
                </div>
            </div>
                <div class="back_img-area audience-area">
                    <img src="{% static 'IMG/index_img/1544004869.png' %}" id="Megami_img" alt="Megami" >
                    <img src="{% static 'IMG/index_img/1544163788-1.png' %}" id="JK_img" alt="JK" >
                </div>

            <div class="login-area">
                <div class="main">
                    <p class="sign" align="center">Login</p>
                    <form class="form1">
                      <input class="un " type="text" align="center" placeholder="Username">
                      <input class="pass" type="password" align="center" placeholder="Password">
                      <!-- <a class="submit" align="center">Login</a> -->
                      <button class="login-btn login"> <span>Login</span> </button>
                      <p class="forgot" align="center"><a href="#">Forgot Password?</p></a>          
                </div>
            </div>
        </div>
    </header>
    <concept>
        <div class="concept">
            <h1 class="concept-message"> Concept </h1>
            <div class="concept-img">
                <img src="{% static 'IMG/index_img/1535965055.png' %}" class="conect-img" alt="conect" >
            </div>
            <div class="concept-container">
                <p class="salon-con">美容師とユーザーをつなげる</p>
                <p class="user-con">サロンとユーザーをつなげる</p>
                <p class="stylist-con">サロンと美容師をつなげる</p>
            </div>
        </div>
    </concept>
    <center>
    <Ability>
        <div class="Ability">
            <h1 class="Ability-message">Ability</h1>
            <div class="Ability-img">
                <img src="{% static 'IMG/index_img/1517047896-1.png' %}"class="Ability-img1" id="Ability-img1" alt="conect" >
                <img src="{% static 'IMG/index_img/1544163784.png' %}" class="Ability-img2" id="Ability-img2" alt="conect" >
            </div>
            <div class="Ability-container">
                <p class="stylist-user">お気に入りの美容室・美容師を探せる</p>
                <p class="salon-user">ビジネス・リクルートに利用できる</p>
                <p class="stylist-salon">容姿の変化や日常を投稿し共有できる</p>
            </div>
        </div>
    </Ability>
    </center>

    
{% endblock %}

Megami_project/Megami_app/templates/logout.html
{% extends "base.html" %}
{% load static %}
    {% block style %}
        <!-- <link rel="stylesheet" href="{% static 'CSS/home.css' %}"> -->
    {% endblock %}
    {% block content %}
    Hello
    {% endblock %}

Megami_project/Megami_app/templates/post_delete.html
{% extends "base.html" %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'CSS/post_delete.css' %}">
    {% endblock %}
{% block content %}
<header>
    <div class="header">
        <div class="header-menu">
            <h1 class="megami-logo header-item"><a href=" {% url 'home' %} " class="logo">Megami</a></h1>
        </div>
      </div>
  </header>

<div class="post_detaile">
    <div class="post_data">
      {% if post_data.image %}
        <img class="rounded detail-img" src="{{ post_data.image.url }}" alt="" />
      {% endif %}
      <div class="post_title">
        <h2>{{ post_data.title }}</h2>
      </div>
      <div class="post_pro">
        <p>{{ post_data.content|linebreaksbr }}</p>
      </div>

      <h5 class="">削除してもよろしいですか</h5>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger delet_button" type="submit">削除</button>
        </form>

      <div class="return_home">
        <a href="/">戻る<i class="fa fa-solid fa-angle-right"></i></a>
      </div>
      
    </div>
  </div>
{% endblock %}

Megami_project/Megami_app/templates/post_detail.html
{% extends "base.html" %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'CSS/post_detaile.css' %}">
    {% endblock %}
    {% block content %}
    <header>
      <div class="header">
          <div class="header-menu">
              <h1 class="megami-logo header-item"><a href=" {% url 'home' %} " class="logo">Megami</a></h1>
          </div>
        </div>
    </header>
    <div class="post_detaile">
      <div class="post_data">
        {% if post_data.image %}
          <img class="rounded detail-img" src="{{ post_data.image.url }}" alt="" />
        {% endif %}
        <div class="post_title">
          <h2>{{ post_data.title }}</h2>
        </div>
        <div class="post_pro">
          <p>{{ post_data.content|linebreaksbr }}</p>
          {% if user.icon == null%}
            <img  class="icon-img" src="/media/{{ post_data.user.image }}">
          {% else %}
            <img class="icon-img" src="{% static 'IMG/home_img/icons8-user-64.png' %}">
          {% endif %}
            <p class="icon-img post_user_pro">{{ post_data.user }}</p>
        </div>

        {% if post_data.user == user %}
        <div class="user_detaile_button">
          <a class="btn btn-warning" href="{% url 'Megami_app:post_edit' post_data.id %}">編集する</a>
          <a class="btn btn-danger" href="{% url 'Megami_app:post_delete' post_data.id %}">削除する</a>
        </div>
        {% endif %}

        <div class="return_home">
          <a href="/">戻る<i class="fa fa-solid fa-angle-right"></i></a>
        </div>
        
      </div>
    </div>

{% endblock %}

Megami_project/Megami_app/templates/post_form.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'CSS/post_form.css' %}">
{% endblock %}
{% block content %}
<main >
    <div class="main">
        <div class="header">
            <h1 class="megami-logo header-item"><a href="/" class="logo">Megami</a></h1>
        </div>
        <div class="post_area">
          <div class="post-title">
            <i class="fas fa-paper-plane"></i>
            <h2>Post</h2>
          </div>
                <div class="Post_container">
                        <!-- <p class="sign" align="center">POST</p> -->
                        <form method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="formpost">
                            <label class="title_label">Title</label>
                            <div class="title_post">{{ form.title }}</div>
                          </div>

                          <div class="formpost">
                            <label class="content_label">Content</label>
                            <div class="title_post">{{ form.content }}</div>
                            
                          </div>
                          <div class="formpost">
                            <label class="upload-label">
                              <i class="fas fa-cloud-upload-alt"></i>
                              Image
                              {{ form.image }}
                            </label>
                          </div>

                          <!-- <button class="" type="submit">投稿する</button> -->
                          <div class="container">
                            <button id="button" type="submit"></button>
                          </div>
                        </form>
                </div>
                <div class="return_home">
                  <a href="#" onclick="history.back()">戻る<i class="fa fa-solid fa-angle-right"></i></a>
                </div>
        </div>
    </div>
</main>
<script type="text/javascript" src="{% static 'JS/post_form.js' %}"></script>
{% endblock %}